### ISSUE TITLE
jser.infoのスライド

### ISSUE THREAD

**Issue by azu** [azu/slide#4]
[JSer.info 200回記念イベント - connpass](http://connpass.com/event/9067/)

世界のJavaScriptを見ようの方のスライド

連想ゲーム的に色々振り返りながら未来の話を軽く触れていく感じのやつ。
(細かいまとまりがあると時間調整がしやすそう)

ブラウザ
- JSer.info始めた頃のブラウザのバージョン
  - Firefox4
  - IE9
  - Chrome10
- IEの変化
- ヘッドレスブラウザの登場
  - [WebkitベースのJavaScriptコマンドラインツール「PhantomJS」 - JSer.info](http://jser.info/post/2888913234/)
- [SlimerJS](http://slimerjs.org/index.html)
- [sdesalas/trifleJS](https://github.com/sdesalas/trifleJS)
- [PhantomJS 2 · ariya/phantomjs Wiki](https://github.com/ariya/phantomjs/wiki/PhantomJS-2)
- PhantomJS APIがデファクトへ
  - [CasperJS, a navigation scripting and testing utility for PhantomJS and SlimerJS](http://casperjs.org/)
  - [Nightmare](http://www.nightmarejs.org/)
- 一方Selenium/WebDriver
- WebDriver
  - [Protractor - end to end testing for AngularJS](http://angular.github.io/protractor/#/)
  - [Leadfoot docs: Index](http://theintern.github.io/leadfoot/)
  - [Nightwatch.js | Node.js powered End-to-End testing framework](http://nightwatchjs.org/)
- IE11がWebDriver サポート
- [August updates for Internet Explorer - IEBlog - Site Home - MSDN Blogs](http://blogs.msdn.com/b/ie/archive/2014/08/13/august-updates-for-internet-explorer.aspx)
- [全国のSeleniumer必読 - Qiita](http://qiita.com/oh_rusty_nail/items/b8ba525d31ea7c522856)

アーキテクチャー
- MV*
- React
- Flux
- isomorphic

リリースノート
- blog
- medium
- Twitter
- Github
- ChangeLog
- コミットから自動生成
- Watchスタイルの変化

Watcher
- 必然的にコミットを追う必要が出てくる
- GitHub Releaseを追うスタイル
- Browser Watcher
- Webkit Watcher
- Mozilla Watcher
- Blink Watcher
- Watch Watcher

ECMAScript
- es-discuss
- TC39 MTG Notes
- Web Spec hosting としての GitHub
- やっぱりGitHub Watcher

CI
- Travis
- Github page
- WebSpecもTravisで自動生成
- Respec

ツール
- リポジトリを見ると色々なメタファイルがある
- JSHint
- ESLint
- JSCS
- https://github.com/jshint/fixmyjs/
- editorconfig
- AST

非同期
- promise
- localforge
- google api
- es6
- stream
- browserify
- gulp
- gruntnext
- web stream api

**Comment by yosuke-furukawa** [comment]
良さそう！

**Comment by azu** [comment]
# ブラウザのバージョン
- rapid releaseでブラウザのバージョンの意識することは少なくなった
  - 特にChromeはバージョン殆ど意識しない
- エンタープライズrelease
- feature-model releaseへ
- TC39 ECMAScript
- バージョンベースではなく機能ベースのリリースへ
- HTML versioning
- Node.js本体のstable/unstableモデル
- semver
- 意味的なversioning

**Comment by azu** [comment]
Watchには抑制する力も必要。
何でも見て追おうとすると破綻する。

via [Rebuild: 62: Wrong Username Mentions (dice)](http://rebuild.fm/62/)

**Comment by azu** [comment]
リリースを追うために自身が変化することは大切ではあるけど、無理はしてはいけない。
スクラップ、RSS、Notification、メールなど自分の好きな形に持ち込むことが大切。

非連続性、非同期である事がストレスフリーである空間を作るのに役立ちそう。

取りこぼしが不安なら取りこぼしを取る方法をいれ二回拾えばいい。

**Comment by azu** [comment]
Webは過渡期という言葉で片付けるには余りにも複雑すぎる気はする。

Web Componentsがどうなるのかという未来が一番見えにくい感じがする。
Custom Elementは既存UIを継承するという点が意味を持ちやすそうで残りそうと思う。
ロジックは結合とかのほうが良いこと多いけどUIは継承の方が形にあうこと多い。

だけどそういう未来を見通せるのはイタコが必要なので、どういう姿勢でみるのかで結果の受け取りからが変わりそう。

未来は突然来るわけはないので、少なくてもそこに至るまでには兆候なりが存在する。
どういう手段でもいいけど、その兆候を捉えられるのが、変化になるのかもしれない。

**Comment by azu** [comment]
### 最新の情報を追う技術の言語化

[ES6+カジュアルトーク](http://connpass.com/event/9113/)の資料でECMAScriptの仕様について調べてたけど、ECMAScriptと言っても色々あるのでどれが最新なのか分からないという問題が起きやすかった。
今回どうやって見ていったのかを少し言語化してみる。

今回の話は**仕様**に限定されたものかもしれない。
- 出発点は[rwaldron/tc39-notes](https://github.com/rwaldron/tc39-notes)だった
- そもそも[rwaldron/tc39-notes](https://github.com/rwaldron/tc39-notes)をどうやって見つけたのかはあんまり記憶にない
- でも恐らく誰かがアクティビティから見つけたはず
- 誰かと言うのは恐らくTC39のメンバだと思う
- このことから分かるのは、やっぱり詳しい人のアクティビティを見るというのが大事なのかと思った
- JavaScriptみたいに進化の早いものは、見つけたものが必ずしも**最新**なのかは分からない
- 逆に何が**最新**なのかは日付以外の重みとなる情報が必要だと思う。
- その重みとなる要素は**人**がやっぱりわかりやすい
- 仕様はそもそも人がいないと成立しないし、最近の仕様は民主的な策定を仕様としてるケースが多い
  - [node-forward](https://github.com/node-forward)
  - [Node.js Advisory Board](https://www.joyent.com/blog/node-js-advisory-board)
- 独裁的でも中心的な人物は決まってくるので、その人を見つけるというのが一番の近道

#### 実例
- ES7で提案されてる仕様は[tc39/ecma262](https://github.com/tc39/ecma262)に載ってる
- それぞれGitHubリポジトリがあるので、そのOwnerがその仕様の中心だと簡単に分かる
- そのOwnerのアクティビティを見ていけばいい
- そのブログとか組織でやってるなら組織とか、Issueとかの活動とか見ればいい
- 直接聞いてしまうのもいいと思う

例) [dslomov-chromium/typed-objects-es7](https://github.com/dslomov-chromium/typed-objects-es7)
- Typed ObjectsはGitHubの方は7ヶ月前に何か止まってる感じがする
- 7ヶ月前に一番ちかいTC39 MTGは2014年4月
- [agendas/04.md at master · tc39/agendas](https://github.com/tc39/agendas/blob/master/2014/04.md)のアジェンダにTyped Objectsの議論がある
- けど[tc39-notes/es6/2014-04 at master · rwaldron/tc39-notes](https://github.com/rwaldron/tc39-notes/tree/master/es6/2014-04)みても何かよく分からない
- だが中心の人はDmitry Lomov, Niko Matsakisの二人だと書いてある
- ブログとかないかをぐぐる
- [Nikoさんのブログ](http://smallcultfollowing.com/babysteps/)
- [Typed Objects Status Report - Baby Steps](http://smallcultfollowing.com/babysteps/blog/2014/04/01/typed-objects-status-report/)というのがある
- [論文](http://smallcultfollowing.com/babysteps/pubs/2014.04.01-TypedObjects.pdf)出して基本的な[973238 – Implement structural arrays for typed objects](https://bugzilla.mozilla.org/show_bug.cgi?id=973238)を立てたとある
- IssueのBlocksとか見ると [578700 – (harmony:typedobjects) [meta] Harmony typed objects (nés binary data)](https://bugzilla.mozilla.org/show_bug.cgi?id=578700) を見ればちょっとづつやってるんだなーという感じがわかる
- なので今実装するために色々やってるんだなー的な状況かなと思った

**Comment by azu** [comment]
HTML5のスケジュールモデル。
ECMAは以外とこれ意識してそう。
http://dev.w3.org/html5/decision-policy/html5-2014-plan.html

**Comment by azu** [comment]
韓国語版について書くの忘れてた

http://wit.nts-corp.com/
